
build:
  image: teaci/msys$$arch
  pull: true
  shell: msys$$arch
  commands:
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-pkg-config cmake zlib-devel
    - git submodule update --init --recursive
    - cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTS=ON -DIOAPI_NO_64=ON .
    - make -j 8
    - ctest -C Release -V

matrix:
  arch:
# Bug with 64-bit MSYS2 on WINE currently, disable temporarily.
#    - 64
    - 32
