version: '{build}'

os:
  - Visual Studio 2015
  - Visual Studio 2017

environment:
  matrix:
  - additional_flags: ""
  - additional_flags: "/std:c++latest"

matrix:
  exclude:
    - additional_flags: "/std:c++latest"
      os: Visual Studio 2015

init: []

install: []

build_script:
  # Set the correct generator
  - IF "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2015" ( SET GEN="Visual Studio 14 2015") ELSE (SET GEN="Visual Studio 15 2017")
  # ZLIB isn't included on Windows, and no package manager has a static,
  # /MT-linked build, so we can download it and build it ourselves
  - appveyor DownloadFile http://zlib.net/zlib-1.2.11.tar.gz -FileName zlib-1.2.11.tar.gz
  - 7z x zlib-1.2.11.tar.gz > NUL
  - 7z x zlib-1.2.11.tar > NUL
  - cd zlib-1.2.11
  - cmake -G %GEN% -DCMAKE_C_FLAGS_RELEASE="/MT"
  - cmake --build . --config Release
  # Configure libxlsxwriter to use the static ZLIB
  - cd ..
  - cmake . -G%GEN% -DBUILD_TESTS=ON -DZLIB_LIBRARY=%APPVEYOR_BUILD_FOLDER%\zlib-1.2.11\Release\zlibstatic.lib -DZLIB_INCLUDE_DIR=%APPVEYOR_BUILD_FOLDER%\zlib-1.2.11
  - cmake --build . --config Release

test_script:
  - ctest -C Release -V
