###############################################################################
#
# Makefile for libxlsxwriter library.
#
# Copyright 2014-2018, John McNamara, jmcnamara@cpan.org
#

include ../Makefile.unit
